# Generated by Django 3.2.16 on 2023-01-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_alter_recipe_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='status',
        ),
        migrations.AddField(
            model_name='recipe',
            name='skill_level',
            field=models.IntegerField(choices=[(0, 'Beginners'), (1, 'Intermediate'), (2, 'Advanced')], default=0),
        ),
    ]
