# Generated by Django 3.2.16 on 2023-01-31 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20230129_0025'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='first_name',
            new_name='profile_first_name',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='last_name',
            new_name='profile_last_name',
        ),
    ]
